### ISSUE TITLE
Composition Length Limit?

### ISSUE THREAD

**Issue by farfromsubtle** [stevenwaterman/musetree#32]
First off, a HUGE thank you for the work you are doing on this. I became quite addicted to making music base on the musenet blog's tool, and your implementation of it is so inspired!

One issue I have noticed however, is that I can't generate past about 1:40 of content? This same limit happens on the musenet blog. Is this just a limit of the model?

**Comment by stevenwaterman** [comment]
Hi! I'm glad you're enjoying MuseTree. I think that it is a fundamental limit of the API. There are a few potential causes I have in mind:

1. For each of the 4 completions in the response, the MuseNet API sends an MP3 of the full song up until that point. That can get very big, and it may be hitting some limit. I don't think this is the issue because I've had compositions last 3+ minutes before, if they're quite slow songs. It seems likely to be a number-of-notes issue than a total-length issue. In any case, i've reached out to the creator on Twitter about asking the API to not send the MP3, which would solve this. No response yet though.

2. The encoding that we send to the API could be too long for the model, and it just causes an error.
3. The model could be too slow with large encodings, and our requests are timing out.

If the issue is with the model, there's not a lot we can do. One option I have in mind is to not send the full encoding, For example, we could just send the last 1000 notes and MuseNet wouldn't know the difference. I'm currently working on a large architecture update for MuseTree that would allow us to do that. The specific issue for that feature is https://github.com/stevenwaterman/musetree/issues/10

**Comment by farfromsubtle** [comment]
Great to hear you already have some solutions/workarounds in mind!

**Comment by stevenwaterman** [comment]
This is implemented in version 2, which is releasing this Sunday, 2020-05-17. The relevant commit is https://github.com/stevenwaterman/musetree/commit/bb70063b7ed3dee49df675bad04f90d265bb8897
