### ISSUE TITLE
New 2.0 Instrument Sounds

### ISSUE THREAD

**Issue by farfromsubtle** [stevenwaterman/musetree#33]
First of all, thank you again for your continued work improving this amazing implementation of musenet. I have been using 2.0 and it feels like a marked improvement especially with the ability to limit the length.

One issue I had: The new instruments seem to by synth-sounding as opposed to emulating the acoustic instruments like piano and guitar. Is this a permanent change?

*edit* I see now with the musenet export option that musetree is now playing back midi within the browser while the rendered instruments are still available. I will look into somehow changing the default sounds of midi playback on my mac.

**Comment by stevenwaterman** [comment]
Yeah I'm well aware that the instruments don't sound as good. It's a permanent change, but they will improve over time. The reason for the change is that we are no longer using the mp3 that MuseNet returns, but generating the audio on the fly using the web audio API. This brings a lot of benefits (such as the encoding length limit, almost 1000x decrease in save file size, and will allow manually editing sections in the future)

However, i'm no musician. I decided that it was more important to get version 2 out there so people could use it while I continue to work on improving the instruments. Currently, drums should sound identical to MuseNet, Piano is reasonably good, and the strings are so-so. Everything else is pretty bad. If you have experience with synths, get in touch and help out!

As you have discovered, there is still the `MuseNet export` option which will request the original high-quality mp3 from musenet. That won't be going away - and if the original sound is important to you then the old version is still available while they improve.

Sadly since the browser isn't actually playing MIDI (there's no way to play midis in the browser natively), you won't be able to change the sounds that play when you're using MuseTree 2

Hope that answers some of your questions, and thanks for raising the issues! It's good to confirm that it sounds a bit crap to others too XD

**Comment by farfromsubtle** [comment]
That's OK, I can use my imagination. The midi export is a lot faster/reliable now so I have just been dropping those into my DAW every couple generations.

Note editing sounds AMAZING. I have spent so much time regenerating a part over and over just hoping it will change in the slight way I want where just grabbing a couple notes would have me on my way!

**Comment by stevenwaterman** [comment]
Yeah, not relying on MuseNet audio is a massive improvement and opens up a lot of new options (but was really hard and required basically a full rewrite :upside_down_face: ) . Even simple things like being able to trim the end of a section and say `I like this section, but the ending is rubbish, cut off the last 5 secs` would be great. Previously, doing anything like that would've meant I had to send a request to musenet after each edit (transferring MBs of data, taking a long time, and probably failing because musenet api returns errors quite often)

The next feature I'm going to be working on is the ability to import a MIDI - which would work as a stop-gap measure for note editing (export to midi, edit, import midi)

I'll open a ticket for note editing - https://github.com/stevenwaterman/musetree/issues/34
